# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170604_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='account',
            new_name='user_account',
        ),
    ]
